networks:
  ai_network:

volumes:
  pg_data:
  ollama_data:
  redis_data:   #Add volume for Redis

services:

  python_ai:
    build: .
    container_name: ai_engineer_python
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "5678:5678"   # ⭐ REQUIRED for debug

    env_file:
      - .env.docker 
    environment:
    - DEBUG=false     # ⭐ toggle debug mode
    - AI__OTLP_ENDPOINT=http://otel-collector:4317
    volumes:
      - ./app:/app/app     # ⭐ hot reload source
    depends_on:
      postgres:
        condition: service_healthy
      ollama:
        condition: service_healthy
      redis:                      # ⭐ ADD
        condition: service_started
      otel-collector:
        condition: service_started
    networks:
      - ai_network


  postgres:
    image: postgres:16
    container_name: ai_engineer_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ai_engineer_db_user
      POSTGRES_PASSWORD: ai_engineer_db_pass
      POSTGRES_DB: ai_engineer_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ai_engineer_db_user -d ai_engineer_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ai_network


  ollama:
    image: ollama/ollama
    container_name: ai_engineer_ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ai_network
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:                           # ⭐ NEW SERVICE
    image: redis:7
    container_name: ai_engineer_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ai_network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: ai_engineer_jaeger
    restart: unless-stopped
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    networks:
      - ai_network

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: ai_engineer_otel
    command:
      - "--config=/etc/otelcol/config.yaml"
    volumes:
      - ./otel-config.yaml:/etc/otelcol/config.yaml
    depends_on:
      - jaeger
    networks:
      - ai_network
